### ISSUE TITLE
Version mismatch on OSX 10.8.4

### ISSUE THREAD

**Issue by vhaasteren** [nirinA/erfa_python#4]
Hi nirinA,

I am starting to help Scott Ransom and others with their new pulsar timing code, and I have been trying to get erfa_python to work. I am currently on an OSX Mountain Lion (10.8.4) distro, and I am seeing some version mismatch between erfa_python and erfa. Note that I also tested it on a virtual machine with Debian, where everything works no problem. Extra info below.

Hope you can help! Thanks,

Rutger

The error I get:

(dev)[ vhaaster dhcp-195-218 ~/local/erfa ] python
Python 2.7.5 (default, Oct 18 2013, 12:58:26) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.75)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _erfa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/vhaaster/env/dev/lib/python2.7/site-packages/_erfa.so, 2): Library not loaded: /Users/vhaaster/local/erfa/lib/liberfa.1.dylib
  Referenced from: /Users/vhaaster/env/dev/lib/python2.7/site-packages/_erfa.so
  Reason: Incompatible library version: _erfa.so requires version 2.0.0 or later, but liberfa.1.dylib provides version 0.0.0
>>> exit()

I basically followed this instruction set to install erfa:
    export INSTDIR=/Users/vhaaster/local/
    git clone https://github.com/liberfa/erfa-fetch.git
    cd erfa-fetch
    python sofa_deriver.py
    cd erfa
    gcc -O2 -I. -c -fPIC *.c
    gcc -shared -o liberfa.so *.o -lm
    cp erfa*.h $INSTDIR/include/
    cp liberfa.so $INSTDIR/lib/liberfa.so.1.0.0
    ln -sf $INSTDIR/lib/liberfa.so.1.0.0 $INSTDIR/lib/liberfa.dylib
    ln -sf $INSTDIR/lib/liberfa.so.1.0.0 $INSTDIR/lib/liberfa.1.dylib

**Comment by nirinA** [comment]
hi Rutger,
please disregard my last request as you already did that.
also, for serious usage, please consider using the astropy package as erfa is now included in it, unless you have to use erfa somewhere without the need of installing anything else than Python.
best regards,

**Comment by vhaasteren** [comment]
Thank you for getting back at me nirinA,

I have indeed discovered that erfa is now included in Astropy (through PINT), so that indeed solves all of my problems. Thank you very much for all your efforts.

Best regards,

Rutger
